### ISSUE TITLE
Connection to SystemDB on Port 39013 with HXE SP04

### ISSUE THREAD

**Issue by gregorwolf** [jungsap/hdiWithoutXSA#1]
Hi Thomas,

thank you for providing this script. I first had some issues to connect to the SystemDB. But with the help of the post [AWS | Multi-tenant - only internal ports available - no 30015 listening](https://answers.sap.com/questions/11807758/aws--multi-tenant---only-internal-ports-available-.html) I've used port 39013 and where able to connect to the SystemDB. Maybe the scripts need adjustment?

Best regards
Gregor

**Comment by jungsap** [comment]
Well of course the ports and hosts used in these scripts are work on my system and only provided as an example. You'll have to adjust for your particular system.  In my system 30013 works because my instance number is 00. I'm assuming you are running HXE where the default instance number is 90.  The 3XX13 or 3XX15 - XX is your instance number.
